[[pages]]
path = "/"
screenshotTimestamp = "2026-04-23T19:05:54Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/7dbde12a-4ad3-4faa-a2c7-6a5f3b985dfd/82c1cce8-f5ee-4ccd-89f7-ec5b844208b9/mYp9Sg8"

[[pages]]
path = "/login"
screenshotTimestamp = "2026-04-23T19:06:27Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/7dbde12a-4ad3-4faa-a2c7-6a5f3b985dfd/82c1cce8-f5ee-4ccd-89f7-ec5b844208b9/SuVtnQN"
